/**
 * The Knowledge Graph Conference blog archive, as data.
 *
 * Scraped once from the live WordPress at
 * `knowledgegraph.tech/wp-json/wp/v2/posts` and checked in, rather than fetched
 * at request time, because the site has to build and render with no network —
 * and because a marketing page that goes blank when someone else's CMS is down
 * is a worse page than a slightly stale one.
 *
 * `excerpt` is the excerpt WordPress itself publishes, not the article body.
 * These posts are substantially guest-authored, so their copyright is not
 * uniformly the conference's to relocate; republishing them in full here would
 * be a rights decision rather than an engineering one. Every post therefore
 * carries its author and a link to the canonical article, and the detail pages
 * declare that canonical URL to search engines so this site never competes with
 * the original for the same words.
 *
 * To refresh: re-run the REST query, regenerate this file, and re-download the
 * featured images into `public/kgc/blog/`. Full-text migration is a follow-up
 * that needs the owner's confirmation of rights plus a WordPress export.
 */

export type Post = {
  /** The live site's own slug, so `/blog/<slug>` mirrors `knowledgegraph.tech/blog/<slug>`. */
  slug: string;
  title: string;
  /** Plain `YYYY-MM-DD`. Publication day, not an instant — see `formatPostDate`. */
  date: string;
  author: string;
  /** The author's archive page on the live site, where WordPress gave us one. */
  authorUrl: string | null;
  categories: string[];
  tags: string[];
  excerpt: string;
  /**
   * `true` when WordPress published no excerpt and this is instead the opening
   * words of the body, shown as a quotation with the canonical link beside it.
   */
  excerptIsQuote: boolean;
  /** The canonical article on knowledgegraph.tech. */
  url: string;
  /**
   * The featured image, downloaded into `public/kgc/blog/` at scrape time.
   *
   * Local rather than hot-linked: `next/image` would need `knowledgegraph.tech`
   * in `images.remotePatterns`, and hot-linking would leave 70 cards dependent
   * on someone else's uptime for the thing that makes them look like cards.
   */
  image: string | null;
  imageWidth: number;
  imageHeight: number;
};

/** Newest first — the order the index renders in, so it is the order stored. */
export const POSTS: Post[] = [
  {
    slug: "kgc-2024-knowledge-graph-named-entity-resolution",
    title: "KGC 2024: Entity-Resolved Knowledge Graphs",
    date: "2025-09-08",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2024", "KGC Talks", "Learning material"],
    tags: ["data lineage", "entity resolution", "graph analytics", "graph visualization", "KGC 2024", "knowledge graph", "LLMs", "Neo4j", "Python", "RAG"],
    excerpt:
      "Please enjoy this talk “Entity-Resolved Knowledge Graphs,” from the Knowledge Graph Conference 2024 given by Paco Nathan, Principal DevRel Engineer at Senzing (also known as the “Gandalf of Graph Technology”). Talk description: Knowledge graphs have spiked recently in popular use, for example in retrieval augmented generation (RAG) methods used to mitigate hallucination in LLMs. Graphs…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2024-knowledge-graph-named-entity-resolution/",
    image: "/kgc/blog/kgc-2024-knowledge-graph-named-entity-resolution.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "knowledge-graph-news-roundup-5-september-2025",
    title: "Fortnightly Knowledge Graph News Roundup [5 September 2025]",
    date: "2025-09-05",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "data integration", "deep learning", "entity resolution", "graph database", "KnowHax", "knowledge graph", "machine learning", "Neo4j", "semantic web"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on September 5th, 2025. KG Community Discussions Ora Lassila lays out “Ora’s Rule of Knowledge Graph Implementation” on the RDF vs. LPG debate Ashleigh Faith has a new video on explaining what a vector is (and why it…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-5-september-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-5-september-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "kgc-2024-data-loss-prevention-knowledge-graph-model",
    title: "KGC 2024: Dowsing for Data: A Unified Knowledge Model for Data Loss Prevention",
    date: "2025-09-01",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2024", "KGC Talks", "Learning material"],
    tags: ["data loss prevention", "data modeling", "graph reasoning", "KGC 2024", "knowledge graph", "knowledge management", "knowledge representation", "LLMs", "natural language processing", "Northrop Grumman"],
    excerpt:
      "Please enjoy this talk “Dowsing for Data: A Unified Knowledge Model for Data Loss Prevention,” from the Knowledge Graph Conference 2024 given by Michael Miller and Zach Tretter from Northrop Grumman. Talk description: A scalable knowledge protection strategy is critical to an organization’s security and success. Companies safeguard sensitive metrics, intellectual property, and information regulated…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2024-data-loss-prevention-knowledge-graph-model/",
    image: "/kgc/blog/kgc-2024-data-loss-prevention-knowledge-graph-model.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "kgc-2024-knowledge-graph-trading-card-game",
    title: "KGC 2024: Creating a Trading Card Game using Knowledge Graphs",
    date: "2025-08-25",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2024", "KGC Talks", "Learning material"],
    tags: ["data modeling", "JavaScript", "JSON", "KGC 2024", "knowledge graph", "knowledge representation", "ontologies", "ontology", "semantic knowledge", "semantic web"],
    excerpt:
      "Please enjoy this talk “Creating a Trading Card Game using Knowledge Graphs,” from the Knowledge Graph Conference 2024 given by Soaib Rashid, Co-Founder and CEO at The Tetraverse Company. Talk description: Tetraverse Trading Card Game (TCG) is a unique blend of strategy and captivating artwork that sets it apart in the competitive trading card game…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2024-knowledge-graph-trading-card-game/",
    image: "/kgc/blog/kgc-2024-knowledge-graph-trading-card-game.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "knowledge-graph-news-roundup-22-august-2025",
    title: "Fortnightly Knowledge Graph News Roundup [22 August 2025]",
    date: "2025-08-22",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "entity resolution", "generative AI", "GraphRAG", "knowledge graph", "machine learning", "open source", "semantic web", "supply chain", "taxonomy"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on August 22nd, 2025. Articles, Editorial, & Hot Takes Game changer? A first look at the Hydra project by Amber Lennox [gdotv blog] How AI-Powered Relational Knowledge Graph Can Help by Jay Yu [Supply & Demand Chain Executive]…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-22-august-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-22-august-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "kgc-2024-composite-queries-multiple-knowledge-graphs",
    title: "KGC 2024: Composite Queries for Multi-Domain Knowledge",
    date: "2025-08-18",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2024", "KGC Talks", "Learning material"],
    tags: ["AI", "data analysis", "data management", "data privacy", "graph analysis", "graph database", "graph visualization", "KGC 2024", "knowledge graph", "ontologies"],
    excerpt:
      "Please enjoy this talk “Composite Queries for Multidomain Knowledge: Span Multiple Graphs without Blending Data,” from the Knowledge Graph Conference 2024 given by David Hughes, Director of Engineering & AI at Graphable (now at Enterprise Knowledge). Talk description: In the rapidly evolving landscape of data management, the ability to effectively handle diverse concerns such…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2024-composite-queries-multiple-knowledge-graphs/",
    image: "/kgc/blog/kgc-2024-composite-queries-multiple-knowledge-graphs.jpg",
    imageWidth: 1000,
    imageHeight: 513,
  },
  {
    slug: "kgc-2024-session-unlocking-the-power-of-knowledge-graphs-in-data-isolation",
    title: "KGC 2024 Session: Unlocking the Power of Knowledge Graphs in Data Isolation",
    date: "2025-08-11",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2024", "KGC Talks", "Learning material"],
    tags: ["compliance", "data governance", "data privacy", "graph theory", "graph visualization", "KGC 2024", "knowledge graph", "knowledge representation", "metadata", "semantic modeling"],
    excerpt:
      "Please enjoy this talk “Unlocking the Power of Knowledge Graphs in Data Isolation,” from the Knowledge Graph Conference 2024 given by Richard Beatch, Semantic Modeling Executive Director, and by Matthew Rawlings, Data Strategy & Head of Product, both from JPMorganChase. Talk description: Many industries are regulated to varying degrees. Regulations frequently impact how…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2024-session-unlocking-the-power-of-knowledge-graphs-in-data-isolation/",
    image: "/kgc/blog/kgc-2024-session-unlocking-the-power-of-knowledge-graphs-in-data-isolation.png",
    imageWidth: 800,
    imageHeight: 445,
  },
  {
    slug: "knowledge-graph-news-roundup-8-august-2025",
    title: "Fortnightly Knowledge Graph News Roundup [8 August 2025]",
    date: "2025-08-08",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "cybersecurity", "entity resolution", "graph database", "GraphRAG", "knowledge graph", "LLMs", "machine learning", "MCP", "semantic web"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on August 8th, 2025. Articles, Editorial, & Resources GraphGeeks in Discussion: Exploring GraphRAG with Neo4j’s Tomaž Bratanič [GraphGeeks] When AI Gets Entities Wrong & What It Costs You [Senzing blog] How SLMs & knowledge graphs supercharge AI [TechRadar]…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-8-august-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-8-august-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-conference-community-survey",
    title: "Share Your Thoughts & Ideas in the KGC Community Survey",
    date: "2025-08-06",
    author: "François Scharffe & Thomas Deely",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/founders-blog-bio-only/",
    categories: ["KGC 2025"],
    tags: ["AI", "graph data science", "graph database", "graph neural network", "KGC 2025", "knowledge graph", "LLMs", "ontologies", "semantic technology", "taxonomy"],
    excerpt:
      "Thank you for making the Knowledge Graph Conference 2025 the best edition ever! Your feedback on the content and experience of KGC is what makes each year better than the last. This summer, we want to take a pulse on some of your ideas for KGC 2026 as we brainstorm about expanding the scope of…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-conference-community-survey/",
    image: "/kgc/blog/knowledge-graph-conference-community-survey.png",
    imageWidth: 800,
    imageHeight: 400,
  },
  {
    slug: "kgc-2024-session-arachne-an-open-source-framework-for-graph-analytics",
    title: "KGC 2024 Session: Arachne: An Open Source Framework for Graph Analytics",
    date: "2025-08-04",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2024", "KGC Talks", "Learning material"],
    tags: ["cybersecurity", "data analysis", "data science", "graph algorithm", "graph analytics", "graph data science", "graph database", "KGC 2024", "knowledge graph", "National Science Foundation"],
    excerpt:
      "Please enjoy this talk “Arachne: An Open Source Framework for Graph Analytics,” from the Knowledge Graph Conference 2024 given by David A. Bader, PhD, Distinguished Professor of Data Science at the New Jersey Institute of Technology (NJIT). Talk description: A real-world challenge in data science is to develop interactive methods for quickly analyzing…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2024-session-arachne-an-open-source-framework-for-graph-analytics/",
    image: "/kgc/blog/kgc-2024-session-arachne-an-open-source-framework-for-graph-analytics.png",
    imageWidth: 833,
    imageHeight: 418,
  },
  {
    slug: "kgc-2024-session-a-workshop-on-throwing-kg-workshops",
    title: "KGC 2024 Session: A Workshop on Throwing KG Workshops",
    date: "2025-07-28",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2024", "KGC Talks", "Learning material"],
    tags: ["Capgemini", "data modeling", "graph technology", "graph visualization", "KGC 2024", "knowledge graph", "knowledge representation", "semantic web", "workshop"],
    excerpt:
      "Please enjoy this presentation “A Workshop on Throwing Workshops” from the Knowledge Graph Conference 2024 given by Veronika Heimsbakk, Knowledge Graph Lead at Capgemini. Workshop description: Welcome to an inspirational and creative meta-workshop on how to throw workshops! We will go hands-on, experience and learn first-hand how we can build successful workshops on outreaching…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2024-session-a-workshop-on-throwing-kg-workshops/",
    image: "/kgc/blog/kgc-2024-session-a-workshop-on-throwing-kg-workshops.png",
    imageWidth: 800,
    imageHeight: 538,
  },
  {
    slug: "knowledge-graph-news-roundup-25-july-2025",
    title: "Fortnightly Knowledge Graph News Roundup [25 July 2025]",
    date: "2025-07-25",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "business intelligence", "entity resolution", "generative AI", "GraphRAG", "knowledge graph", "LLMs", "MCP", "ontology", "semantic web"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on July 25th, 2025. KG Community Discussions Transduction vs abduction in LLMs [Tony Seale on LinkedIn] Show HN: OntoCast – ontology-assisted KG generation [Hacker News] Protégé is Not Just an IDE – It’s a Programming Language for Ontologists…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-25-july-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-25-july-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-18-july-2025",
    title: "Early Summer Knowledge Graph News Roundup [18 July 2025]",
    date: "2025-07-18",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "data science", "graph database", "GraphRAG", "knowledge graph", "knowledge management", "LLMs", "ontology", "OWL", "semantic web"],
    excerpt:
      "Welcome back to another news roundup from around the knowledge graph industry covering all of May, June, and July through the week ending on July 18th, 2025. KG Community Discussions Show HN: OntoCast: ontology-assisted KG generation [Hacker News] Building Meaning That Lasts: What the Semantic Web Can Learn from Software [LinkedIn] Articles, Editorial, & Hot…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-18-july-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-18-july-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "thank-you-for-a-wonderful-knowledge-graph-conference-2025",
    title: "Thank You for a Wonderful Knowledge Graph Conference 2025!",
    date: "2025-07-15",
    author: "François Scharffe & Thomas Deely",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/founders-blog-bio-only/",
    categories: ["KGC 2025", "Knowledge Graph News"],
    tags: ["AI", "artificial intelligence", "graph database", "HCLS", "healthcare", "KnowHax", "knowledge graph", "LLMs", "ontologies", "semantic technology"],
    excerpt:
      "Wow! What an amazing experience it was to host this year’s Knowledge Graph Conference for you all. We don’t know about you, but out of the 7 years we’ve organized KGC, this was the best year yet. It was so enjoyable getting to see everyone, meet new members of the KG community and catch up…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/thank-you-for-a-wonderful-knowledge-graph-conference-2025/",
    image: "/kgc/blog/thank-you-for-a-wonderful-knowledge-graph-conference-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "paco-nathan-knowledge-graph-ai-language-interview-part-1",
    title: "An Interview with Paco Nathan on AI Realism & the Language of Knowledge Graphs [Part 1]",
    date: "2025-05-02",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["KGC 2025", "Knowledge Graph News"],
    tags: ["AI", "graph neural network", "graph technology", "graph visualization", "GraphRAG", "knowledge graph", "LLMs", "ontology", "Paco Nathan", "RDF"],
    excerpt:
      "The man, the myth, the legend: Paco Nathan warrants no introduction. Everyone who works with graph technology – whether in academia, startups, government, or commercial enterprises – has come across something Paco has designed, invented, popularized, patented, engineered, or written. That, or you’ve bumped into him at a conference, and probably more than once…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/paco-nathan-knowledge-graph-ai-language-interview-part-1/",
    image: "/kgc/blog/paco-nathan-knowledge-graph-ai-language-interview-part-1.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-25-april-2025",
    title: "Weekly Knowledge Graph News Roundup [25 April 2025]",
    date: "2025-04-25",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "bioinformatics", "graph visualization", "KnowHax", "knowledge graph", "LLMs", "open source", "Paco Nathan", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on April 25th, 2025. KG Community Discussions A new graphy agentic thought strategy: Knowledge Graph of Thoughts (KGoT) by Russell Jurney [LinkedIn] Articles, Editorial, & Hot Takes RAG isn’t dead. It’s just getting started by Dominik Tomicevic [Memgraph…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-25-april-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-25-april-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-18-april-2025",
    title: "Weekly Knowledge Graph News Roundup [18 April 2025]",
    date: "2025-04-18",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "bioinformatics", "entity resolution", "graph visualization", "KnowHax", "knowledge graph", "LLMs", "semantic layer", "semantic systems", "semantic web"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on April 18th, 2025. Articles, Editorial, & Hot Takes An obituary for Cyc – “the greatest monument to logical AGI” by Yuxi Tech Deep Dive & Applications Tutorial: Unifying LLMs & Knowledge Graphs for Question Answering: Recent Advances…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-18-april-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-18-april-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-11-april-2025",
    title: "Weekly Knowledge Graph News Roundup [11 April 2025]",
    date: "2025-04-11",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "bioinformatics", "graph visualization", "KnowHax", "knowledge graph", "LLMs", "machine learning", "open source", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on April 11th, 2025. Articles, Editorial, & Hot Takes The Dat(a)ing Game by Dean Allemang [Medium] Future of Data Analysis & Graph Visualization with Paco Nathan & Matthieu Besozzi [Senzing blog] Knowledge Graph Events Featured Event: Hackathon: KnowHax…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-11-april-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-11-april-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-4-april-2025",
    title: "Weekly Knowledge Graph News Roundup [4 April 2025]",
    date: "2025-04-04",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "DeepSeek", "graph visualization", "GraphRAG", "information architecture", "KnowHax", "knowledge graph", "neurosymbolic AI", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on April 4th, 2025. Knowledge Graph Jobs Senior Support Engineer (Remote Germany / Walldorf) – metaphacts Senior Software Engineer (Remote Germany / Walldorf) – metaphacts Technical Consultant (Remote Germany / Walldorf) – metaphacts Staff Software Engineer, Education (Hybrid…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-4-april-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-4-april-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-28-march-2025",
    title: "Fortnightly Knowledge Graph News Roundup [28 March 2025]",
    date: "2025-03-28",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "graph database", "graph technology", "GraphRAG", "knowledge engineering", "knowledge graph", "knowledge management", "ontology", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on March 28th, 2025. Articles & Editorial SAP CTO: Human oversight always needed even as AI advances [FutureCIO] Why we’re continuing to invest in Dgraph [Hypermode blog] New KG Tech & Solutions G.V() is now Compatible with Kuzu,…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-28-march-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-28-march-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "robert-metcalfe-future-ai-knowledge-graphs-interview",
    title: "An Interview with Bob Metcalfe on the Future of AI, Knowledge Graphs & More",
    date: "2025-03-24",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["KGC 2025", "Knowledge Graph News"],
    tags: ["AI", "artificial intelligence", "blockchain", "Bob Metcalfe", "computer engineering", "computer science", "knowledge graph", "OriginTrail", "semantic web", "supply chain"],
    excerpt:
      "It’s rare to meet a mind like Robert Metcalfe’s. Someone nearly six decades deep into their career – with nearly six decades of achievements to match – is worth listening to when they muse on the future of their field. “Bob,” as friends and colleagues call him, has certainly had to eat his words when…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/robert-metcalfe-future-ai-knowledge-graphs-interview/",
    image: "/kgc/blog/robert-metcalfe-future-ai-knowledge-graphs-interview.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-14-march-2025",
    title: "Weekly Knowledge Graph News Roundup [14 March 2025]",
    date: "2025-03-14",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "entity resolution", "generative AI", "graph neural network", "KnowHax", "knowledge engineering", "knowledge graph", "ontology", "RDF", "semantic web"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on 14 March 2025. Research & Papers Accurate POI recommendation for random groups with improved graph neural networks and a multi-negotiation model [Scientific Reports] New KG Tech & Solutions This little AI phone has some wild ideas using…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-14-march-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-14-march-2025.png",
    imageWidth: 600,
    imageHeight: 200,
  },
  {
    slug: "building-enterprise-information-architecture",
    title: "Building an Enterprise Information Architecture: Top-Down or Bottom-Up, Which Is Better?",
    date: "2025-03-11",
    author: "The metaphacts Team",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/metaphacts_team/",
    categories: ["KGC 2025", "Learning material"],
    tags: ["business objects", "EIA", "enterprise architecture", "enterprise information architecture", "information architecture", "knowledge graph", "metaphacts", "semantic knowledge modeling", "semantic layer", "semantic model"],
    excerpt:
      "metaphacts is a Gold Sponsor of the Knowledge Graph Conference 2025. Get your ticket today or learn more about sponsorship opportunities. *** Executing any type of enterprise-wide change can seem intimidating due to the processes involved and the need for alignment among various stakeholders and departments…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/building-enterprise-information-architecture/",
    image: "/kgc/blog/building-enterprise-information-architecture.jpg",
    imageWidth: 800,
    imageHeight: 400,
  },
  {
    slug: "knowledge-graph-news-roundup-7-march-2025",
    title: "Weekly Knowledge Graph News Roundup [7 March 2025]",
    date: "2025-03-07",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "GraphRAG", "information architecture", "KnowHax", "knowledge engineering", "knowledge graph", "ontology", "semantic data", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on March 7th, 2025. Knowledge Graph Jobs Lead Ontology Engineer, Semantic Data Modeling (Copenhagen) – the LEGO Group Jr. Solution Architect (Remote / U.S.) – Stardog Database Analysis & Development Manager – Ontology / Knowledge Engineering (Hybrid /…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-7-march-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-7-march-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-28-february-2025",
    title: "Weekly Knowledge Graph News Roundup [28 February 2025]",
    date: "2025-02-28",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["information architecture", "knowledge engineering", "knowledge graph", "LLMs", "natural language processing", "ontology", "open source", "RDF", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on February 28th, 2025. KG Community & Discussions GraphGeeks in Discussion with William Lyon: From Neo4j to Dgraph by Amy Hodler [GraphGeeks] Call for Papers, Presentations & More Call for Workshop Proposals – CausalNeSy | Portoroz, Slovenia |…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-28-february-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-28-february-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-21-february-2025",
    title: "Weekly Knowledge Graph News Roundup [21 February 2025]",
    date: "2025-02-21",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "DeepSeek", "enterprise information architecture", "generative AI", "GraphRAG", "knowledge graph", "LLMs", "ontology", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on 21 February 2025. Articles, Editorial, & Hot Takes DeepSeek’s AI “breakthrough” isn’t what it seems [Nikkei Asia] Knowledge Graph Events Workshop: Hands-on with Agentic GraphRAG – San Francisco – Monday, 24 February Hackathon: Enterprise RAG Challenge –…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-21-february-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-21-february-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-14-february-2025",
    title: "Fortnightly Knowledge Graph News Roundup [14 February 2025]",
    date: "2025-02-14",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "DeepSeek", "information architecture", "knowledge engineering", "knowledge graph", "knowledge management", "LLMs", "ontology", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on February 14th, 2025. KG Community & Discussions Tony Seale & Jacobus Geluk discuss what the release of DeepSeek’s R1 model means for enterprises [LinkedIn] Knowledge Graph Jobs Student Trainee, Knowledge Management/Librarian (Washington, DC / Atlanta / Seattle)…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-14-february-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-14-february-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-31-january-2025",
    title: "Weekly Knowledge Graph News Roundup [31 January 2025]",
    date: "2025-01-31",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "deep learning", "DeepSeek", "graph visualization", "knowledge graph", "knowledge management", "ontologies", "Paco Nathan", "semantic web", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on January 31st, 2025. KG Community & Discussions Robert Caulk posits that DeepSeek has a critical truth and knowledge-context problem [LinkedIn] News & Articles DeepSeek: the Chinese AI app that has the world talking [BBC] DeepSeek crashes Nvidia…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-31-january-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-31-january-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-24-january-2025",
    title: "Weekly Knowledge Graph News Roundup [24 January 2025]",
    date: "2025-01-24",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "information architecture", "knowledge engineering", "knowledge graph", "LLMs", "natural language processing", "Neo4j", "ontology", "RDF", "taxonomy"],
    excerpt:
      "Welcome back to another weekly news roundup from around the knowledge graph industry for the week ending on January 24th, 2025. Articles, Editorial, & Hot Takes AbbVie’s head of genomics research on the transformative power of AI [McKinsey] Are Machines Truly Thinking? Modern AI Systems Have Finally Achieved Turing’s Vision [SciTechDaily] AI in 2025: 5…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-24-january-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-24-january-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-17-january-2025",
    title: "Fortnightly Knowledge Graph News Roundup [17 January 2025]",
    date: "2025-01-17",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "data engineering", "graph database", "graph neural network", "GraphRAG", "KnowHax", "knowledge graph", "LLMs", "ontologies", "semantic web"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on January 17th, 2025. 2025 Predictions, Articles, & Hot Takes Tony Seale – the Knowledge Graph Guy – shares his predictions for knowledge graphs in 2025 [LinkedIn] Michael Iantosca has only one, bold prediction for 2025 [LinkedIn] Jay…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-17-january-2025/",
    image: "/kgc/blog/knowledge-graph-news-roundup-17-january-2025.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "metaphacts-kgc-new-resource-hub",
    title: "metaphacts & The Knowledge Graph Conference Launch the New Resource Hub",
    date: "2024-12-18",
    author: "Paige Barrett",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/paige/",
    categories: ["Conference news", "Learning material"],
    tags: ["AI", "artificial intelligence", "financial services", "graph technology", "healthcare", "knowledge graph", "knowledge modeling", "metaphacts", "semantic knowledge", "workshop"],
    excerpt:
      "Learn all about the brand-new Knowledge Graph Conference Resource Hub (built by metaphacts) and explore past KGC talks, presentations, and workshops…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/metaphacts-kgc-new-resource-hub/",
    image: "/kgc/blog/metaphacts-kgc-new-resource-hub.png",
    imageWidth: 800,
    imageHeight: 435,
  },
  {
    slug: "knowledge-graph-news-roundup-13-december-2024",
    title: "Fortnightly Knowledge Graph News Roundup [13 December 2024]",
    date: "2024-12-13",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "generative AI", "graph neural network", "GraphRAG", "knowledge engineering", "knowledge graph", "knowledge management", "LLMs", "machine learning", "semantic web"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on December 13th, 2024. Knowledge Graph Jobs Knowledge Engineer (Hybrid/Remote, Helsinki) – In Parallel Postdoc: Knowledge-informed reasoning about the harmfulness of internet memes (Amsterdam) – VU Amsterdam Articles, Editorial & Hot Takes How AI is Transforming Traditional Business…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-13-december-2024/",
    image: "/kgc/blog/knowledge-graph-news-roundup-13-december-2024.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "knowledge-graph-news-roundup-29-november-2024",
    title: "Fortnightly Knowledge Graph News Roundup [29 November 2024]",
    date: "2024-11-29",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "generative AI", "graph database", "graph neural network", "GraphRAG", "knowledge graph", "LLMs", "natural language processing", "ontology", "semantic web"],
    excerpt:
      "Welcome back to another fortnightly news roundup from around the knowledge graph industry for the week ending on November 29th, 2024 KG Community & Discussions Juan Sequeda reflects on 1 year after publishing his co-authored paper on knowledge graphs, LLMs and enterprise SQL databases [LinkedIn] A video by Paco Nathan presents an overview of GraphRAG…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-29-november-2024/",
    image: "/kgc/blog/knowledge-graph-news-roundup-29-november-2024.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "call-for-speakers",
    title: "Call for Speakers: Come Present at Knowledge Graph Conference 2025!",
    date: "2024-11-21",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Conference news", "KGC 2025"],
    tags: ["AI", "artificial intelligence", "Call for Speakers", "Cornell Tech", "graph technology", "knowledge graph", "LLMs", "New York City", "ontologies", "semantic layer"],
    excerpt:
      "Submit your proposal to speak and present at the Knowledge Graph Conference 2025, on everything from AI, knowledge graphs, LLMs, semantic tech, and more…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/call-for-speakers/",
    image: "/kgc/blog/call-for-speakers.jpg",
    imageWidth: 1024,
    imageHeight: 538,
  },
  {
    slug: "sponsor-knowledge-graph-conference",
    title: "Connect Your Brand with KG Experts: Sponsor the Knowledge Graph Conference 2025",
    date: "2024-11-19",
    author: "Poya Osgouei",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/poya/",
    categories: ["Conference news", "KGC 2025"],
    tags: ["AI", "AWS", "Cornell Tech", "data orchestration", "GraphRAG", "healthcare", "knowledge graph", "life sciences", "New York City", "vector database"],
    excerpt:
      "Join the conversation with knowledge graph experts from around the globe when you sponsor KGC 2025 from May 5-9, 2025 at Cornell Tech in New York City…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/sponsor-knowledge-graph-conference/",
    image: "/kgc/blog/sponsor-knowledge-graph-conference.jpg",
    imageWidth: 1024,
    imageHeight: 537,
  },
  {
    slug: "knowledge-graph-news-roundup-15-november-2024",
    title: "Fortnightly Knowledge Graph News Roundup [15 November 2024]",
    date: "2024-11-15",
    author: "Bryce Merkl Sasaki",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/bryce-merkl-sasaki/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "data science", "generative AI", "GraphRAG", "Graphwise", "healthcare", "knowledge graph", "LLMs", "machine learning", "semantic web"],
    excerpt:
      "In this new blog series, we hope to highlight some of the most relevant and interesting articles from around the knowledge graph industry. Here’s your inaugural news roundup for October & November for the week ending on November 15th, 2024. Community & Discussions Michael Pool proposes we all stop using the word “semantics” so much…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graph-news-roundup-15-november-2024/",
    image: "/kgc/blog/knowledge-graph-news-roundup-15-november-2024.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
  {
    slug: "in-person-vs-virtual-conference-tickets",
    title: "KGC 2025: What’s Included for In-Person vs. Virtual Conference Tickets?",
    date: "2024-10-31",
    author: "Paige Barrett",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/paige/",
    categories: ["Conference news", "KGC 2025"],
    tags: ["AI", "artificial intelligence", "Cornell Tech", "graph data science", "knowledge graph", "LLMs", "networking", "New York City", "virtual conference", "virtual networking"],
    excerpt:
      "Discover which Knowledge Graph Conference ticket type is best for you: Want to stream it all online? Or meet colleagues and experts at Cornell Tech in NYC?",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/in-person-vs-virtual-conference-tickets/",
    image: "/kgc/blog/in-person-vs-virtual-conference-tickets.jpg",
    imageWidth: 1024,
    imageHeight: 538,
  },
  {
    slug: "knowledge-graphs-ai-2025",
    title: "Knowledge Graphs & AI: Better Together at KGC 2025",
    date: "2024-10-29",
    author: "François Scharffe & Thomas Deely",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/founders-blog-bio-only/",
    categories: ["Conference news", "KGC 2025"],
    tags: ["artificial intelligence", "generative AI", "graph technology", "GraphRAG", "knowledge engineering", "knowledge graph", "LLMs", "ontologies", "RAG", "vector database"],
    excerpt:
      "Discover what the founders of the Knowledge Graph Conference have in store for the 7th edition of KGC happening this May 5-9, 2025 at Cornell Tech in NYC…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/knowledge-graphs-ai-2025/",
    image: "/kgc/blog/knowledge-graphs-ai-2025.jpg",
    imageWidth: 1024,
    imageHeight: 538,
  },
  {
    slug: "kgc-2023-knowledge-your-code-morgan-stanley",
    title: "KGC 2023: The Knowledge in Your Code",
    date: "2024-08-12",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2023", "KGC Talks", "Learning material"],
    tags: ["data governance", "data lineage", "data management", "financial services", "graph technology", "KGC 2023", "knowledge engineering", "knowledge graph", "knowledge representation", "semantic technology"],
    excerpt:
      "Please enjoy this talk “The Knowledge in Your Code,” from the Knowledge Graph Conference 2023 given by Stephen Goldbaum, Executive Director & Distinguished Engineer at Morgan Stanley. Talk description: Business application developers put a wealth of business knowledge into their code. Too often, aside from executing, that information is left untapped for knowledge engineering purposes…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2023-knowledge-your-code-morgan-stanley/",
    image: "/kgc/blog/kgc-2023-knowledge-your-code-morgan-stanley.jpg",
    imageWidth: 480,
    imageHeight: 360,
  },
  {
    slug: "kgc-2023-healthcare-life-sciences-knowledge-graph-synthea-chatgpt",
    title: "KGC 2023: Building a Healthcare & Life Sciences Knowledge Graph",
    date: "2024-08-05",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2023", "KGC Talks", "Learning material"],
    tags: ["AI", "artificial intelligence", "connected data", "graph databases", "graph technology", "healthcare", "KGC 2023", "knowledge graph", "life sciences", "LLMs"],
    excerpt:
      "Please enjoy this talk “Building a Healthcare & Life Sciences Knowledge Graph with Synthea & ChatGPT,” from the Knowledge Graph Conference 2023 given by Dr. Jans Aasman, CEO of Franz Inc. Talk description: Jans Aasman introduces a plug-and-play healthcare knowledge graph for hospitals, showcasing how large language models like ChatGPT can automatically answer questions and…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2023-healthcare-life-sciences-knowledge-graph-synthea-chatgpt/",
    image: "/kgc/blog/kgc-2023-healthcare-life-sciences-knowledge-graph-synthea-chatgpt.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "kgc-2023-ubs-knowledge-graph-building-a-connected-data-catalog",
    title: "KGC 2023: UBS Knowledge Graph: Building a Connected Data Catalog",
    date: "2024-07-29",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2023", "KGC Talks", "Learning material"],
    tags: ["AI", "connected data", "data architecture", "data management", "financial services", "graph technology", "KGC 2023", "knowledge graph", "semantic technology", "UBS"],
    excerpt:
      "Please enjoy this talk “UBS Knowledge Graph: Building a Connected Data Catalog,” from the Knowledge Graph Conference 2023 given by Gregor Wobbe, Head of Data Architecture at UBS. Talk description: UBS is building a new firm-wide data platform that will empower every employee to harness AI, data, and analytics to gain valuable insights for its…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2023-ubs-knowledge-graph-building-a-connected-data-catalog/",
    image: "/kgc/blog/kgc-2023-ubs-knowledge-graph-building-a-connected-data-catalog.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "kgc-2023-fair-data-solutions-pharmaceutical-research",
    title: "KGC 2023: Building FAIR Solutions & Knowledge Graphs for Pharmaceutical Research",
    date: "2024-07-22",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2023", "KGC Talks", "Learning material"],
    tags: ["AI", "data management", "FAIR data", "healthcare", "KGC 2023", "knowledge graph", "knowledge management", "pharmaceuticals", "semantic layer", "semantic technology"],
    excerpt:
      "Please enjoy this talk “Building FAIR Solutions & Knowledge Graphs for Research in a Large Pharmaceutical Organization,” from the Knowledge Graph Conference 2023 given by John Apathy, Chief Solutions Officer at XponentL Data. Talk description: John Apathy’s keynote at the Knowledge Graph Conference 2023 addresses challenges faced by healthcare and pharmaceutical companies due to inadequate…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2023-fair-data-solutions-pharmaceutical-research/",
    image: "/kgc/blog/kgc-2023-fair-data-solutions-pharmaceutical-research.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "kgc-2023-semantic-recommender-system-case-studies",
    title: "KGC 2023: Semantic Recommendation Engines Case Studies",
    date: "2024-07-15",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2023", "KGC Talks", "Learning material"],
    tags: ["enterprise architecture", "financial services", "government", "healthcare", "information architecture", "KGC 2023", "knowledge graph", "knowledge representation", "recommender system", "semantic data"],
    excerpt:
      "Please enjoy this talk “Semantic Recommendation Engines Case Studies: Bringing Enterprise Information Discovery to the 21st Century,” from the Knowledge Graph Conference 2023 given by Sara Duane and Sara Nash, Senior and Principal Consultants, respectively, at Enterprise Knowledge LLC. Talk description: Content personalization and recommendation engines are pervasive in today’s society. They power some…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2023-semantic-recommender-system-case-studies/",
    image: "/kgc/blog/kgc-2023-semantic-recommender-system-case-studies.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "kgc-2023-knowledge-graph-driven-recommender-system",
    title: "KGC 2023: Knowledge Graph-Driven Recommendations",
    date: "2024-07-08",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2023", "KGC Talks", "Learning material"],
    tags: ["AI", "data privacy", "IKEA", "KGC 2023", "knowledge graph", "ontologies", "RDF", "recommender system", "semantic technology", "semantic web"],
    excerpt:
      "Please enjoy this talk “Knowledge Graph-Driven Recommendations,” from the Knowledge Graph Conference 2023 given by Katariina Kari, Lead Ontologist at Inter IKEA Systems. Talk description: The IKEA Knowledge Graph includes information about complementary products, their benefits, and some safety precautions that customers should know. This information is captured on a general level and allows IKEA…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2023-knowledge-graph-driven-recommender-system/",
    image: "/kgc/blog/kgc-2023-knowledge-graph-driven-recommender-system.jpg",
    imageWidth: 800,
    imageHeight: 450,
  },
  {
    slug: "kgc-2022-panel-knowledge-graph-architecture-where-are-we-and-where-are-we-going",
    title: "KGC 2022 Panel: Knowledge Graph Architecture: Where Are We & Where Are We Going?",
    date: "2022-10-07",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2022", "KGC Talks", "Learning material"],
    tags: ["data architecture", "education", "KGC 2022", "knowledge graph", "knowledge management"],
    excerpt:
      "Please enjoy this panel discussion “Knowledge Graph Architecture: Where Are We & Where Are We Going?” from the Knowledge Graph Conference 2022 shared by Sara Nash, Juan Sequeda, and Gregor Wobbe. Panel discussion summary: The panelists discussed the following topics: The state of knowledge graph architecture today Where should we be going? Lessons learned…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2022-panel-knowledge-graph-architecture-where-are-we-and-where-are-we-going/",
    image: "/kgc/blog/kgc-2022-panel-knowledge-graph-architecture-where-are-we-and-where-are-we-going.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "kgc-2022-panel-graph-data-science-and-knowledge-graphs",
    title: "KGC 2022 Panel: Graph Data Science & Knowledge Graphs",
    date: "2022-10-07",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2022", "KGC Talks", "Learning material"],
    tags: ["data science", "graph data science", "GraphAware", "KGC 2022", "knowledge graph", "Neo4j", "Oracle", "TigerGraph"],
    excerpt:
      "Please enjoy this panel discussion “Graph Data Science & Knowledge Graphs,” from the KGC 2022 moderated by Dr. François Scharffe, Co-Founder of the Knowledge Graph Conference. Panel participants: Participating in the discussion was Dr. Alicia Frame, Neo4j; Dr. Jay Yu, TigerGraph; Dr. Souripriya Das, Oracle; Dr. Giuseppe Futia, GraphAware. The discussion was moderated by Dr…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2022-panel-graph-data-science-and-knowledge-graphs/",
    image: "/kgc/blog/kgc-2022-panel-graph-data-science-and-knowledge-graphs.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "kgc-2022-talk-how-to-build-a-customer-360-knowledge-graph-for-fintech-gupta-jere-intuit",
    title: "KGC 2022 Talk: How to Build a Customer 360 Knowledge Graph for FinTech",
    date: "2022-09-27",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2022", "KGC Talks", "Learning material"],
    tags: ["AI", "customer 360", "data architecture", "data engineering", "financial services", "fintech", "KGC 2022", "knowledge graph", "machine learning"],
    excerpt:
      "Please enjoy this talk “How To Build A Customer 360 Knowledge Graph for FinTech,” from the Knowledge Graph Conference 2022 given by Amit Jere, Vice President, and by Gautam Gupta, Group Manager, both at Intuit. Talk description: This KGC 2022 sessions describes the journey of Jere and Gupta to build a Customer 360 financial…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2022-talk-how-to-build-a-customer-360-knowledge-graph-for-fintech-gupta-jere-intuit/",
    image: "/kgc/blog/kgc-2022-talk-how-to-build-a-customer-360-knowledge-graph-for-fintech-gupta-jere-intuit.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "kgc-2022-talk-agile-principles-in-knowledge-graph-development-borislav-iordanov-semantic-arts",
    title: "KGC 2022 Talk: Agile Principles in Knowledge Graph Development",
    date: "2022-09-27",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2022", "KGC Talks", "Learning material"],
    tags: ["AI", "ETL", "KGC 2022", "knowledge graph", "ontologies", "Semantic Arts", "semantic technology", "software development", "taxonomy"],
    excerpt:
      "Please enjoy this presentation “Agile Principles in Knowledge Graph Development” from the Knowledge Graph Conference 2022 given by Borislav Iordanov at Semantic Arts. Talk summary: Part of the KGC 2022 “Ontologies & Taxonomies” series is “Agile Principles in Knowledge Graph Development” delivered by Borislav Iordanov of Semantic Arts. The ontologist covers the application of…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2022-talk-agile-principles-in-knowledge-graph-development-borislav-iordanov-semantic-arts/",
    image: "/kgc/blog/kgc-2022-talk-agile-principles-in-knowledge-graph-development-borislav-iordanov-semantic-arts.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "kgc-2022-talk-a-taxonomy-of-graph-analytics-harry-powell-tigergraph",
    title: "KGC 2022 Talk: A Taxonomy of Graph Analytics",
    date: "2022-09-27",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2022", "KGC Talks", "Learning material"],
    tags: ["data analytics", "data science", "financial services", "graph analysis", "graph analytics", "graph data science", "KGC 2022", "knowledge graph", "manufacturing", "taxonomy"],
    excerpt:
      "Please enjoy this talk “A Taxonomy of Graph Analytics,” from the Knowledge Graph Conference 2022 given by Harry Powell, Head of Industry Solutions at TigerGraph as part of KGC’s graph data science series. ﻿ asdf Talk description: In his presentation, “A Taxonomy Of Graph Analytics,” Powell shares a taxonomy of graph data analytics that reduces…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2022-talk-a-taxonomy-of-graph-analytics-harry-powell-tigergraph/",
    image: "/kgc/blog/kgc-2022-talk-a-taxonomy-of-graph-analytics-harry-powell-tigergraph.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "2022-talk-beyond-homophily-in-graph-neural-networks-prof-danai-koutra-uni-of-michigan-amazon",
    title: "2022 Talk: Beyond Homophily In Graph Neural Networks (GNNs)",
    date: "2022-09-27",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["KGC 2022", "KGC Talks", "Learning material"],
    tags: ["AI", "graph neural network", "KGC 2022", "knowledge graph", "semantic technology"],
    excerpt:
      "Please enjoy this talk “Beyond Homophily in Graph Neural Networks (GNNs),” from the Knowledge Graph Conference 2024 given by Danai Koutra, Professor at the University of Michigan. Talk description: In this talk, the University of Michigan’s Professor Danai Koutra presents her group’s research on identifying effective graph neural network (GNN) designs and introduces a new…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/2022-talk-beyond-homophily-in-graph-neural-networks-prof-danai-koutra-uni-of-michigan-amazon/",
    image: "/kgc/blog/2022-talk-beyond-homophily-in-graph-neural-networks-prof-danai-koutra-uni-of-michigan-amazon.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "metadata-day-2020",
    title: "Metadata Day 2020 [Workshop Summary]",
    date: "2021-01-27",
    author: "Paco Nathan",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/paconathan/",
    categories: ["Knowledge Graph News", "Learning material"],
    tags: ["connected data", "data governance", "data science", "graph visualization", "knowledge graph", "machine learning", "metadata", "ontology", "open source", "semantic technology"],
    excerpt:
      "For a full day on December 14, 2020, LinkedIn sponsored a virtual workshop called Metadata Day, followed by a public online meetup called Metaspeak. View videos of the event on their website including a set of lightning talks provided by several of the speakers. The gist is that circa 2018, the pending regulatory compliance for…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/metadata-day-2020/",
    image: "/kgc/blog/metadata-day-2020.png",
    imageWidth: 1024,
    imageHeight: 527,
  },
  {
    slug: "public-vs-private-graphs",
    title: "The Case for Knowledge Graphs: Private vs. Public Graphs",
    date: "2020-10-21",
    author: "Paco Nathan",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/paconathan/",
    categories: ["Knowledge Graph News", "Learning material"],
    tags: ["data governance", "financial services", "Google", "healthcare", "knowledge graph", "machine learning", "metadata", "open source", "Python", "recommender system"],
    excerpt:
      "It’s an interesting time to be working with knowledge graphs. A time of stark contrasts in realizations. On the one hand, I talk with many people who would otherwise be quite expert about machine learning use cases who say, “Yeah, well, no one really uses knowledge graphs in production.” On the other hand, there are…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/public-vs-private-graphs/",
    image: "/kgc/blog/public-vs-private-graphs.jpg",
    imageWidth: 1024,
    imageHeight: 630,
  },
  {
    slug: "5-questions-with-michael-atkin",
    title: "5 Questions with Michael Atkin",
    date: "2020-10-12",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Knowledge Graph News", "Learning material"],
    tags: ["data governance", "data management", "knowledge graph", "ontology", "OWL", "RDF", "semantic technology"],
    excerpt:
      "1. Tell us about yourself. I have a strange and sordid history. I’ve been an analyst and advocate for data management since 1985. I started with publishers–the owners of intellectual property–as they discovered concepts associated with the principles of data management. After publishing, I concentrated my efforts on the financial industry, learning how data goes…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/5-questions-with-michael-atkin/",
    image: "/kgc/blog/5-questions-with-michael-atkin.jpeg",
    imageWidth: 400,
    imageHeight: 400,
  },
  {
    slug: "geo-graphs-in-gov",
    title: "Geo Graphs in Government",
    date: "2020-09-23",
    author: "Paco Nathan",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/paconathan/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "deep learning", "graph database", "knowledge graph", "machine learning", "metadata", "ontology", "OWL", "semantic model", "semantic technology"],
    excerpt:
      "When it comes to early-adopters for AI technology, U.S. federal government agencies may not be the first examples that come to mind. My perspective is skewed since my first full-time job using email, internetworking, data visualization, inference, etc., were in the U.S. Army and NASA in the 1980s. Since then I’ve had other roles in…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/geo-graphs-in-gov/",
    image: "/kgc/blog/geo-graphs-in-gov.png",
    imageWidth: 1024,
    imageHeight: 385,
  },
  {
    slug: "5-questions-with-matthias-sesboue",
    title: "5 Questions with Matthias Sesboüé",
    date: "2020-09-11",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "knowledge graph", "machine learning", "Neo4j", "ontology", "RDF", "recommender system", "Semantic Arts", "semantic web", "SPARQL"],
    excerpt:
      "Tell us about yourself. I’m French, and I’ve just finished a Master’s degree in computer engineering studies with a major in machine learning. What are you working on? I start a Ph.D. in October 2020, with a company called TraceParts. They offer 3D models of various industrial equipment parts on their website, where suppliers list…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/5-questions-with-matthias-sesboue/",
    image: "/kgc/blog/5-questions-with-matthias-sesboue.jpeg",
    imageWidth: 400,
    imageHeight: 400,
  },
  {
    slug: "interview-with-oshani",
    title: "5 Questions with Oshani Seneviratne",
    date: "2020-08-24",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "healthcare", "IBM", "knowledge graph", "natural language processing", "ontologies", "semantic technology", "semantic web"],
    excerpt:
      "Healthier eating for diabetics with the RPI + IBM Food Knowledge Graph Tell us about your project. The food knowledge graph (or foodkg) is a joint project between Rensselaer Polytechnic Institute and IBM (part of the IBM AI Horizons Network). The project’s official name is “Health Empowerment through Analytics Learning and Semantics”, or HEALS. We…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/interview-with-oshani/",
    image: "/kgc/blog/interview-with-oshani.png",
    imageWidth: 569,
    imageHeight: 250,
  },
  {
    slug: "focus-kgs-for-food",
    title: "Focus: Knowledge Graphs for Food",
    date: "2020-08-24",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "COVID-19", "graph algorithm", "graph analytics", "healthcare", "knowledge graph", "machine learning", "ontology", "recommender system", "semantic search"],
    excerpt:
      "Dan Barber, the James Beard award-winning chef who pioneered the farm-to-table movement, has a single, elegant term for the complexity of molecules, processes, and sequences that underpins great food: flavor. Like great chefs, computer scientists grapple with complexity, seeking elegant ways to model and analyze increasingly complex–or perhaps, flavorful–phenomena. Across many business verticals, we are…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/focus-kgs-for-food/",
    image: "/kgc/blog/focus-kgs-for-food.png",
    imageWidth: 1024,
    imageHeight: 404,
  },
  {
    slug: "paco-nathan-i-see-lots-of-future-in-kg-work",
    title: "5 Questions with Paco Nathan",
    date: "2020-07-30",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Knowledge Graph News"],
    tags: ["AI", "COVID-19", "deep learning", "graph algorithm", "graph database", "knowledge graph", "machine learning", "natural language processing", "open source", "Paco Nathan"],
    excerpt:
      "Tell us about yourself! I’m Paco Nathan from Derwen. Links to relevant projects, books, videos, articles, etc. can be found here. During the early 1980s, I got started in machine learning and dove into neural networks. After the “AI Winter” I also worked in telecom and network engineering, up until the 2000s when I started…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/paco-nathan-i-see-lots-of-future-in-kg-work/",
    image: "/kgc/blog/paco-nathan-i-see-lots-of-future-in-kg-work.jpg",
    imageWidth: 1024,
    imageHeight: 683,
  },
  {
    slug: "kgc-attendee-analysis",
    title: "KGC 2020 Attendee Data Analysis",
    date: "2020-07-30",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["KGC 2020", "knowledge graph"],
    excerpt:
      "Check out this data of attendees to the virtual Knowledge Graph Conference (KGC) 2020, including titles, industries, locations, and companies:",
    excerptIsQuote: true,
    url: "https://www.knowledgegraph.tech/blog/kgc-attendee-analysis/",
    image: "/kgc/blog/kgc-attendee-analysis.png",
    imageWidth: 512,
    imageHeight: 512,
  },
  {
    slug: "special-events-at-kgc-2020-newsletter-issue-09",
    title: "Special Events at KGC 2020 – Newsletter Issue 09",
    date: "2020-04-27",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["AI", "artificial intelligence", "big data", "COVID-19", "graph database", "graph technology", "healthcare", "KGC 2020", "knowledge graph", "semantic technology"],
    excerpt:
      "Hi there, The Knowledge Graph Conference 2020 is coming in less than a week! Are you ready to be dazzled by the stardom of our speakers this year? Here’s a moment of unveiling our special events at the KGC 2020. KGC 2020Workshop – Personal Health Knowledge Graphs May 5th, 9 am –…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/special-events-at-kgc-2020-newsletter-issue-09/",
    image: "/kgc/blog/special-events-at-kgc-2020-newsletter-issue-09.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "kgc-2020-agenda-is-now-live-kgc-newsletter-issue-08",
    title: "KGC 2020 Agenda is now live – KGC Newsletter Issue 08",
    date: "2020-04-16",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["COVID-19", "data governance", "data management", "graph analytics", "KGC 2020", "knowledge graph", "ontology", "semantic search", "semantic technology", "startup pitch"],
    excerpt:
      "Hi everyone, The Knowledge Graph Conference 2020 agenda is now live! Check it out. May 4-5 Workshops & Tutorials 2 workshops and 7 tutorials on building the state of the art KGs Schedule May 6-7 Main Conference 30 speakers of KG pioneers and leaders sharing vision for KG innovations Schedule KGC 2020 Tickets Join over 130…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-2020-agenda-is-now-live-kgc-newsletter-issue-08/",
    image: "/kgc/blog/kgc-2020-agenda-is-now-live-kgc-newsletter-issue-08.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "kgc-newsletter-issue-07",
    title: "More on KGC 2020 Speakers, Workshops, Startup Pitch – KGC Newsletter Issue 07",
    date: "2020-04-05",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["AI", "COVID-19", "drug discovery", "education", "IBM", "KGC 2020", "knowledge graph", "Neo4j", "recommender system", "startup pitch"],
    excerpt:
      "Hi everyone, Hope you are doing well. This week, we are thrilled to announce the following newly confirmed speakers to present at the Knowledge Graph Conference 2020. KGC 2020 Speakers Ora Lassila, Amazon Web Services Are Knowledge Graphs a good thing? What does it take to build one? David Kamien, CEO, Mind-Alliance Systems How…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-newsletter-issue-07/",
    image: "/kgc/blog/kgc-newsletter-issue-07.jpg",
    imageWidth: 1024,
    imageHeight: 576,
  },
  {
    slug: "kgc-newsletter-issue-06",
    title: "KGC 2020 Speakers Announcement – KGC Newsletter Issue 06",
    date: "2020-03-26",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["AI", "COVID-19", "graph analytics", "GraphQL", "KGC 2020", "knowledge graph", "machine learning", "ontologies", "OWL", "semantic web"],
    excerpt:
      "Hi everyone, We hope that you, your loved ones, and your communities are well and safe. With the Knowledge Graph Conference 2020 coming in one month, we have been busy getting everything ready for this transformational virtual conference – a global feast of learning and sharing on knowledge graphs. Today, we are happy and thrilled…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-newsletter-issue-06/",
    image: "/kgc/blog/kgc-newsletter-issue-06.jpg",
    imageWidth: 1024,
    imageHeight: 512,
  },
  {
    slug: "kgc-update-covid-19-response",
    title: "KGC 2020: A Digital Experience",
    date: "2020-03-25",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["COVID-19", "KGC 2020", "knowledge graph"],
    excerpt:
      "The health and wellbeing of our community is our top priority. Due to the growing concern around the coronavirus (COVID-19), and in alignment with the best practices laid out by the CDC, WHO and other relevant entities, The Knowledge Graph Conference has decided to reimagine KGC 2020, which will still take place from May 4th…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-update-covid-19-response/",
    image: "/kgc/blog/kgc-update-covid-19-response.png",
    imageWidth: 569,
    imageHeight: 250,
  },
  {
    slug: "kgc-newsletter-issue-04-2",
    title: "KGC 2020 Goes Virtual – KGC Newsletter Issue 05",
    date: "2020-03-19",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020", "Knowledge Graph News"],
    tags: ["AI", "COVID-19", "DeepMind", "education", "Fluree", "KGC 2020", "machine learning", "ontology", "Stanford University", "Stardog"],
    excerpt:
      "KGC 2020 Goes Virtual Hi everyone, The health and well-being of the KGC community is our top priority. Due to the growing concern around the coronavirus (COVID-19), and following the best practices recommended by the CDC and WHO, we have decided to reimagine KGC 2020 to be a complete virtual experience that takes place on…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-newsletter-issue-04-2/",
    image: "/kgc/blog/kgc-newsletter-issue-04-2.jpg",
    imageWidth: 1024,
    imageHeight: 512,
  },
  {
    slug: "kgc-newsletter-issue-04",
    title: "KGC 2020 Announcement – KGC Newsletter Issue 04",
    date: "2020-03-12",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["AI", "Columbia University", "COVID-19", "education", "graph database", "healthcare", "KGC 2020", "knowledge graph", "natural language processing", "New York City"],
    excerpt:
      "Hi everyone, We are closely monitoring the latest developments on the Coronavirus (COVID-19), and will be following the recommendations of the World Health Organization and CDC accordingly. As of now, the Knowledge Graph Conference 2020 is to take place on May 6-7 at Columbia University, as scheduled. However, the workshops and tutorials on May 4-5…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-newsletter-issue-04/",
    image: "/kgc/blog/kgc-newsletter-issue-04.png",
    imageWidth: 569,
    imageHeight: 250,
  },
  {
    slug: "kgc-newsletter-issue-03",
    title: "Latest KG News, Ideas & Insights – KGC Newsletter Issue 03",
    date: "2020-02-19",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020", "Knowledge Graph News"],
    tags: ["AI", "connected data", "KGC 2020", "knowledge graph", "knowledge management", "link prediction", "Microsoft", "ontologies", "ontology"],
    excerpt:
      "Last CallProposals for Presentation KGC 2020 presentations are 20-min talks where you can share all topics related to knowledge graph technology: implementations, case-studies, software, representation formalisms, schemas and ontologies, data integration, and more. Deadline Feb 28, 2020 Hot & NewKGC 2020 Regular Tickets Available RecapKG Meetup Marta Lopata, Chief Growth Officer from ThinkNum demonstrated KGBase…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-newsletter-issue-03/",
    image: "/kgc/blog/kgc-newsletter-issue-03.jpg",
    imageWidth: 1024,
    imageHeight: 512,
  },
  {
    slug: "kgc-newsletter-issue-02",
    title: "Early-Bird Tickets | Top KG News, Ideas and Insights – KGC Newsletter Issue 02",
    date: "2020-02-06",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["AI", "artificial intelligence", "data integration", "financial services", "Google", "GraphQL", "KGC 2020", "knowledge graph", "ontologies", "RDF"],
    excerpt:
      "Hello everyone,We have some exciting news to share with you! KGC 2020 Early Registration Is Open Early bird tickets are available until Feb 15. We are thrilled to announceKGC 2020 Workshops & Tutorials Workshops Knowledge Graphs for Social Good (KGSG) – Best Practices, Methods and ChallengesOrganizers: Vivek Khetan (Accenture Labs), Colin Puri (Accenture Labs), Lambert…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/kgc-newsletter-issue-02/",
    image: "/kgc/blog/kgc-newsletter-issue-02.jpg",
    imageWidth: 1024,
    imageHeight: 512,
  },
  {
    slug: "jan-newsletter-01",
    title: "Happy 2020 | News from the KG Community – KGC Newsletter Issue 01",
    date: "2020-01-08",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020", "Knowledge Graph News"],
    tags: ["AI", "artificial intelligence", "data engineer", "digital transformation", "explainable AI", "Google", "KGC 2020", "knowledge graph", "machine learning", "OntoText"],
    excerpt:
      "Hi there! Happy New Year ???? Hope your 2020 is off to a great start. In our 1st edition of the year, we’d like to share some top stories, news and opportunities from the knowledge graph community. Call for Workshops and Tutorials As many of you know, Knowledge Graph Conference 2020 is seeking proposals for…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/jan-newsletter-01/",
    image: "/kgc/blog/jan-newsletter-01.png",
    imageWidth: 569,
    imageHeight: 250,
  },
  {
    slug: "intro-blog",
    title: "Welcome to the Knowledge Graph Conference Blog",
    date: "2019-07-25",
    author: "François Scharffe",
    authorUrl: "https://www.knowledgegraph.tech/blog/author/lechatpito/",
    categories: ["Conference news", "KGC 2020"],
    tags: ["KGC 2020", "knowledge graph"],
    excerpt:
      "As we relaunch the website, we are also opening this blog as a space to share information about the Knowledge Graph Conference, interviews with the speakers, and other community news related to knowledge graphs. We hope you enjoy reading us and are looking forward to seeing you at the next edition of the conference. Cordially,…",
    excerptIsQuote: false,
    url: "https://www.knowledgegraph.tech/blog/intro-blog/",
    image: "/kgc/blog/intro-blog.png",
    imageWidth: 1000,
    imageHeight: 500,
  },
];

/**
 * Every category that actually has posts, most-used first.
 *
 * Derived rather than typed out so the filter row cannot drift from the data:
 * offering a filter that matches nothing is the specific failure this avoids.
 */
export const POST_CATEGORIES: { name: string; count: number }[] = (() => {
  const counts = new Map<string, number>();
  for (const post of POSTS) {
    for (const category of post.categories) {
      counts.set(category, (counts.get(category) ?? 0) + 1);
    }
  }
  return [...counts.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
})();

export function getPost(slug: string): Post | undefined {
  return POSTS.find((post) => post.slug === slug);
}

/**
 * `2025-09-08` → `8 September 2025`.
 *
 * `Date.UTC` + a UTC formatter, exactly as `formatDayHeading` in `site.ts` does
 * and for the same reason: these are plain publication dates, and
 * `new Date('2025-09-08')` formatted locally reads a day early west of
 * Greenwich — which would silently misdate half this archive.
 */
export function formatPostDate(date: string): string {
  const [y, m, d] = date.split('-').map(Number);
  return new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(Date.UTC(y, m - 1, d)));
}

/** The posts in a category, or all of them when `category` is not a real one. */
export function postsInCategory(category: string | null): Post[] {
  if (!category) return POSTS;
  return POSTS.filter((post) => post.categories.includes(category));
}
